version: '3.8'
services:
  server:
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=myStrongPassword12#
    volumes:
      - sqldata:/var/opt/mssql
    container_name: sqlserver
    deploy:
      resources:
        reservations:
          cpus: '2'
          memory: 2GB
    ports:
      - 1433:1433
    image: mcr.microsoft.com/mssql/server:2022-latest
  contacts:
    container_name: webapp
    ports:
      - 80:80
    image: simonatafrovahomiesscr.azurecr.io/homies
    domainname: simonatafrova
    restart: on-failure
    build:
      dockerfile: ./Dockerfile
volumes:
  sqldata:
    driver: azure_file
    driver_opts:
      share_name: sql-volume
      storage_account_name: simonahomiesstorageacc
